# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HMM-UNPAM
email: hmm_unpam@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Himpunan Mahasiswa Manajemen Universitas Pamulang
  
  
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hmm-unpam.com" # the base hostname & protocol for your site

#sidebar
default-image: logo-hmm.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.
#footer
built-by: Humas & Infokom
copyright:
   name: HMM-UNPAM
   link: 'http://hmm-unpam.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: hmm-unpam

#social
facebook: http://facebook.com/hmm.unpam
intsagram: http://instagram.com/hmm_unpam
twitter: http://twitter.com/@hmm_unpam

#facebook like box
fb-app-id: 
fb-page-url: https://www.facebook.com/hmm.unpam/
fb-page-title: HMM-UNPAM

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
